### ISSUE TITLE
14-cyfrowy REGON

### ISSUE THREAD

**Issue by bbprojectnet** [pacerit/laravel-polish-validation-rules#14]
Cześć,

Czy jest szansa na dodanie obsługi 14-cyfrowego REGONU?

https://pl.wikipedia.org/wiki/REGON

**Comment by WiktorPacer** [comment]
Cześć, Pewnie ; ) Niedługo się tym zajmę.

**Comment by WiktorPacer** [comment]
Dodane 2 nowe wersje:
* Laravel 9.x -> 5.2.0
* Laravel 10.x -> 6.1.0
