### ISSUE TITLE
Laravel 11 - problem

### ISSUE THREAD

**Issue by bpre** [pacerit/laravel-polish-validation-rules#17]
Wygląda na to, że niestety nie działa z Laravel 11:

  Problem 1
    - Root composer.json requires pacerit/laravel-polish-validation-rules ^6.1 -> satisfiable by pacerit/laravel-polish-validation-rules[6.1.0].
    - pacerit/laravel-polish-validation-rules 6.1.0 requires illuminate/support ^10.0 -> found illuminate/support[v10.0.0, ..., v10.48.10] but these were not loaded, likely because it conflicts with another require.

**Comment by WiktorPacer** [comment]
Dzięki za zgłoszenie. Niedługo wypuszczę nową wersję ze wsparciem dla Laravel 11.x.

**Comment by WiktorPacer** [comment]
Dodana nowa wersja 7.0.0 wspierająca Laravel w wersji 11.x.
