### ISSUE TITLE
Błędna walidacja PESEL

### ISSUE THREAD

**Issue by bbprojectnet** [pacerit/laravel-polish-validation-rules#7]
Dla przypadków takich jak np:

- 00000000000
- 44444444444

**Comment by WiktorPacer** [comment]
Dzięki za zgłoszenie. Pracuje nad poprawką.

**Comment by WiktorPacer** [comment]
Dodane nowe wersje paczki:
* 5.2.0 - dla Laravel 9.x
* 4.2.0 - dla Laravel 8.x
Starsze wersje nie zostały zaktualizowane.

Lista zmian - https://github.com/pacerit/laravel-polish-validation-rules/blob/master/CHANGELOG.md

**Comment by bbprojectnet** [comment]
Dzięki wielkie :)
